[project]
name = "h0rv-github-io"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "markdown2>=2.5.3",
    "pyyaml>=6.0.2",
]

[dependency-groups]
dev = [
    "ruff>=0.11.8",
]
